### ISSUE TITLE
zero_init for res_gate

### ISSUE THREAD

**Issue by PROPHETE-pro** [yz93/LAVT-RIS#15]
I notice that though the weight for the two nn.Linear are initialized to zero in the __init__ function, when loading swin weight in segmentation.py it will be randomly initialized one more time. That means, even at the first time of model forward in MMbasiclayer, the weight for the nn.Linear is not 0.

It does not matter much, but a reminder

**Comment by yz93** [comment]
Thank you so much for catching this and sharing here. You are absolutely right.

Those two lines of init code never took any effect because initialization was overwritten later in segmentation.py.

Did you happen to test what happens when we really initialize the gates to 0s? My (possibly useless) intuition was that having 0 multi-modal flow (into the purely visual Swin features) at the beginning of the training is a safe strategy as it avoids potential disruption of features. And of course, due to wrong code that thought has never been realized and tested...

**Comment by PROPHETE-pro** [comment]
Guess how I found this, I tried to add an additional residual attention layer for language text, but never receive a comparable result with your baselines. So I made some of pdb.set_trace() in both __init__ function and forward function, and notice that the Linear was never 0-initialized. 

It is not hard to make a really 0-init Linear layer, but I'm afraid "AF is short on GPUs" (dialogues in <Midway>), and your results are still promising, so don't care about 0-init very much.... I need to find where my BUG take place...

**Comment by yz93** [comment]
Cool mate! Thanks again for pointing this out. And best of luck with your research and finding that annoying bug (I am sure it's nothing and probably has already gone away by now...). 

On another note, right now the code has un-used parameters, i.e., the last stage language gates, as the last stage PWAM outputs are directly used for segmentation and never sent back to the backbone. So if you want, within each MMBasicSwinLayer, you can check whether the current layer is the last stage of Swin and if so, choose not to declare the language gates (i.e., self.res_gate).

This way you can change find_unused_parameters in DistributedDataParallel in train.py to False. This should make training slightly faster, in principle. I haven't benchmarked by how much, but that is the way things are supposed to be. I set find_unused_parameters to False initially due to a bug in huggingface 3.0.2 that required it, and did not bother to improve the code after I fixed the bug. Anyway, this is not super important but just a note.

Cheers.
